services:
  app: # Контейнер с вэб-приложением
    image: clarityofmind/todo-app-final
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment: # Переменные окружения
      PGHOST: postgres
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: todos
  postgres: # Контейнер с СУБД
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment: # Переменные окружения
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
volumes:
  todo-postgres-data: